package com.apex.module.lease.enums;

public enum LeaseEventType {
    // Saga initiation
    LEASE_CREATION_REQUESTED,
    PROPERTY_RESERVED,
    PROPERTY_RESERVATION_FAILED,
    TENANT_VALIDATION_REQUESTED,
    TENANT_VALIDATED,
    TENANT_VALIDATION_FAILED,
    LEASE_CREATED,
    LEASE_CREATION_FAILED,
    // Compensation
    CANCEL_PROPERTY_RESERVATION,
    PROPERTY_RESERVATION_CANCELLED
}
