
server:

  port: ${GATEWAY_PORT:8080}

  forward-headers-strategy: framework

  shutdown: graceful



spring:

  application:

    name: gateway-service

  data:

    redis:

      host: ${REDIS_HOST:redis}

      port: 6379

      timeout: 2000ms

  cloud:

    gateway:

      globalcors:

        cors-configurations:

          '[/**]':

            allowedOrigins: "*"

            allowedMethods: GET,POST,PUT,DELETE,OPTIONS,PATCH

            allowedHeaders: "*"

            allowCredentials: true

      routes:

        - id: auth-service

          uri: http://auth_service:8080

          predicates:

            - Path=/api/auth/**

          filters:

            - name: RequestRateLimiter

              args:

                redis-rate-limiter.replenishRate: 5

                redis-rate-limiter.burstCapacity: 15

                key-resolver: "#{@ipKeyResolver}"

        - id: mpesa-callback

          uri: http://mpesa_service:8080

          predicates:

            - Path=/api/payments/callback

        - id: mpesa-service

          uri: http://mpesa_service:8080

          predicates:

            - Path=/api/mpesa/**

          filters:

            - RewritePath=/api/mpesa/(?<segment>.*), /api/payments/${segment}

            - TenantFilter

            - JwtAuthFilter

        - id: property-service

          uri: http://property_service:8080

          predicates:

            - Path=/api/properties/**

          filters:

            - TenantFilter

            - JwtAuthFilter

        - id: payment-service

          uri: http://payment_service:8080

          predicates:

            - Path=/api/payments/**

          filters:

            - RewritePath=/api/payments/(?<segment>.*), /api/v1/${segment}

            - TenantFilter

            - JwtAuthFilter



jwt:

  secret: ${JWT_SECRET:CHANGE_THIS_TO_64_CHAR_RANDOM_STRING_IN_PRODUCTION_32_BYTES_MIN}

management:

  endpoints:

    web:

      exposure:

        include: health,info,gateway

