
upstream auth_service { server auth_service:8080; }

upstream gateway_service { server gateway_service:8080; }



limit_req_status 429;

limit_conn_status 429;



server {

    listen 80;

    server_name localhost;



    location /api/auth/ {

        limit_req zone=login_limit burst=15 nodelay;

        proxy_pass http://auth_service:8080/api/auth/;

    }

    location / {

        proxy_pass http://gateway_service:8080;

        proxy_set_header Host $host;

        proxy_set_header X-Real-IP $remote_addr;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_set_header X-Tenant-ID $http_x_tenant_id;

        proxy_set_header Upgrade $http_upgrade;

        proxy_set_header Connection $connection_upgrade;

    }

}

