
#!/usr/bin/env bash

set -euo pipefail



if [ -f .env ]; then

    set -a

    . ./.env

    set +a

fi



DB_USER="${POSTGRES_USER:-rentflow}"

DB_NAME="${POSTGRES_DB:-rentflow}"

COMPOSE="docker compose --env-file .env"



# Prevent Git Bash from mangling paths in args like `public.users`

export MSYS_NO_PATHCONV=1



declare -A TABLES

TABLES[auth-service]="users refresh_tokens outbox_events"

TABLES[lease-service]="leases"

TABLES[property-management-service]="properties units landlords tenants"

TABLES[maintainance-ticket-service]="tickets"

TABLES[payment-service]="payments invoices security_deposits deposit_deductions payment_splits payment_methods payment_accounts audit_logs"

TABLES[mpesa-service]="transactions"



SERVICES="auth-service lease-service property-management-service maintainance-ticket-service payment-service mpesa-service"



# Single-line command, no backslash continuation

dump_table() {

    $COMPOSE exec -T postgres pg_dump -U "$DB_USER" -d "$DB_NAME" --schema-only --no-owner --no-privileges -t "public.$1"

}



for service in $SERVICES; do

    dir="$service/src/main/resources/db/migration"

    mkdir -p "$dir"

    out="$dir/V1__baseline.sql"



    {

        echo "-- ============================================================================"

        echo "-- V1 — Baseline for $service"

        echo "-- Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"

        echo "-- ============================================================================"

        echo ""

        echo "Do not edit this file after it has been applied. Create a new V2__*.sql instead."

        echo ""

    } > "$out"



    for table in ${TABLES[$service]}; do

        echo "-- ---------- $table ----------" >> "$out"

        dump_table "$table" >> "$out" 2>&1 || echo "-- ERROR dumping $table" >> "$out"

        echo "" >> "$out"

    done



    echo "$(wc -l < "$out") lines  →  $out"

done



echo ""

echo "Done."

